"""
Tests for colgo_white_salmon_city_council spider.
"""

from datetime import datetime
from os.path import dirname, join

import pytest
from city_scrapers_core.constants import CITY_COUNCIL, PASSED
from city_scrapers_core.utils import file_response
from freezegun import freeze_time

from city_scrapers.spiders.colgo_white_salmon_city_council import (
    ColgoWhiteSalmonCityCouncilSpider,
)

spider = ColgoWhiteSalmonCityCouncilSpider()

# ============================================================================
# Test calendar page parsing (source: calendar HTML → meeting detail URLs)
# ============================================================================
calendar_response = file_response(
    join(dirname(__file__), "files", "colgo_white_salmon_city_council_calendar.html"),
    url=(
        "https://www.whitesalmonwa.gov/calendar/month/2025-01"
        "?field_microsite_tid=All&field_microsite_tid_1=27"
    ),
)

# Get the requests generated by parse (these are requests to detail pages)
calendar_requests = list(spider.parse(calendar_response))


def test_calendar_request_count():
    """Test that calendar parsing extracts filtered meeting links."""
    # Fixture has 3 city-council-meeting links after filtering by meeting_keyword
    assert len(calendar_requests) == 3


def test_calendar_request_url():
    """Test that extracted URLs point to meeting detail pages."""
    urls = [req.url for req in calendar_requests]
    assert any("city-council-meeting" in url for url in urls)


def test_calendar_request_meta_contains_calendar_start():
    """Test that calendar parsing passes calendar_start datetime in request meta."""
    # All requests should have calendar_start in meta from the calendar grid
    for req in calendar_requests:
        assert "calendar_start" in req.meta
        # Should be ISO format datetime string
        assert "T" in req.meta["calendar_start"]


# ============================================================================
# Test detail page parsing (source: detail HTML → Meeting item)
# ============================================================================
@pytest.fixture(scope="module")
def parsed_items():
    detail_response = file_response(
        join(dirname(__file__), "files", "colgo_white_salmon_city_council_detail.html"),
        url="https://www.whitesalmonwa.gov/citycouncil/page/city-council-meeting-152",
    )
    with freeze_time("2025-12-22"):
        return list(spider.parse_meeting(detail_response))


@pytest.fixture(scope="module")
def parsed_item(parsed_items):
    return parsed_items[0] if parsed_items else None


def test_count(parsed_items):
    assert len(parsed_items) == 1


def test_title(parsed_item):
    assert parsed_item["title"] == "City Council Meeting"


def test_description(parsed_item):
    # Uses default description from About page
    assert "City Council of White Salmon" in parsed_item["description"]
    assert "part-time City Attorney" in parsed_item["description"]


def test_classification(parsed_item):
    assert parsed_item["classification"] == CITY_COUNCIL


def test_start(parsed_item):
    assert parsed_item["start"] == datetime(2025, 12, 17, 18, 0)


def test_end(parsed_item):
    assert parsed_item["end"] is None


def test_time_notes(parsed_item):
    assert parsed_item["time_notes"] == ""


def test_id(parsed_item):
    assert (
        parsed_item["id"]
        == "colgo_white_salmon_city_council/202512171800/x/city_council_meeting"
    )


def test_status(parsed_item):
    assert parsed_item["status"] == PASSED


def test_location(parsed_item):
    assert parsed_item["location"] == {
        "name": "City's Council Chambers",
        "address": "119 NE Church Ave, White Salmon, WA 98672",
    }


def test_source(parsed_item):
    assert (
        parsed_item["source"]
        == "https://www.whitesalmonwa.gov/citycouncil/page/city-council-meeting-152"
    )


def test_links(parsed_item):
    links = parsed_item["links"]
    # Check that we have agenda and packet links
    assert any(link["title"] == "Agenda" for link in links)
    assert any(link["title"] == "Agenda Packet" for link in links)


def test_all_day(parsed_item):
    assert parsed_item["all_day"] is False


# ============================================================================
# Test _parse_start fallback pattern
# ============================================================================
@pytest.fixture(scope="module")
def parsed_item_with_calendar_start():
    """Test that calendar_start from meta takes priority over detail page date."""
    detail_response = file_response(
        join(dirname(__file__), "files", "colgo_white_salmon_city_council_detail.html"),
        url="https://www.whitesalmonwa.gov/citycouncil/page/city-council-meeting-152",
    )
    # Inject calendar_start in meta (simulating what parse() does)
    detail_response.meta["calendar_start"] = "2026-03-04T18:00:00-08:00"
    with freeze_time("2025-12-22"):
        items = list(spider.parse_meeting(detail_response))
    return items[0] if items else None


def test_start_uses_calendar_meta(parsed_item_with_calendar_start):
    """Test that _parse_start prefers calendar_start from meta."""
    # Should use the calendar_start from meta, not the detail page date
    assert parsed_item_with_calendar_start["start"] == datetime(2026, 3, 4, 18, 0)


def test_start_fallback_to_detail_page(parsed_item):
    """Test that _parse_start falls back to detail page when no calendar_start."""
    # The parsed_item fixture has no calendar_start in meta, so it uses detail page
    assert parsed_item["start"] == datetime(2025, 12, 17, 18, 0)
