"""
Tests for colgo_white_salmon_civil_service spider.
"""

from datetime import datetime
from os.path import dirname, join

from city_scrapers_core.constants import COMMISSION, PASSED
from city_scrapers_core.utils import file_response
from freezegun import freeze_time

from city_scrapers.spiders.colgo_white_salmon_civil_service import (
    ColgoWhiteSalmonCivilServiceSpider,
)

spider = ColgoWhiteSalmonCivilServiceSpider()

# ============================================================================
# Test calendar page parsing (source: calendar HTML → meeting detail URLs)
# ============================================================================
calendar_response = file_response(
    join(dirname(__file__), "files", "colgo_white_salmon_civil_service_calendar.html"),
    url=(
        "https://www.whitesalmonwa.gov/calendar/month/2025-01"
        "?field_microsite_tid=All&field_microsite_tid_1=231"
    ),
)

# Get the requests generated by parse (these are requests to detail pages)
calendar_requests = list(spider.parse(calendar_response))


def test_calendar_request_count():
    """Test that calendar parsing extracts meeting links."""
    assert len(calendar_requests) >= 1


def test_calendar_request_url():
    """Test that extracted URLs point to meeting detail pages."""
    urls = [req.url for req in calendar_requests]
    assert any("civil-service-commission-meeting" in url for url in urls)


# ============================================================================
# Test detail page parsing (source: detail HTML → Meeting item)
# ============================================================================
detail_response = file_response(
    join(dirname(__file__), "files", "colgo_white_salmon_civil_service_detail.html"),
    url=(
        "https://www.whitesalmonwa.gov/civilservice/page/"
        "civil-service-commission-meeting-1"
    ),
)

freezer = freeze_time("2025-12-22")
freezer.start()
parsed_items = list(spider.parse_meeting(detail_response))
freezer.stop()

parsed_item = parsed_items[0] if parsed_items else None


def test_count():
    assert len(parsed_items) == 1


def test_title():
    assert parsed_item["title"] == "Civil Service Commission Meeting"


def test_description():
    assert "Civil Service Commission will meet" in parsed_item["description"]


def test_classification():
    assert parsed_item["classification"] == COMMISSION


def test_start():
    assert parsed_item["start"] == datetime(2025, 1, 15, 17, 0)


def test_end():
    assert parsed_item["end"] is None


def test_time_notes():
    assert parsed_item["time_notes"] == ""


def test_id():
    expected = (
        "colgo_white_salmon_civil_service/202501151700/x/"
        "civil_service_commission_meeting"
    )
    assert parsed_item["id"] == expected


def test_status():
    assert parsed_item["status"] == PASSED


def test_location():
    assert parsed_item["location"] == {
        "name": "City's Council Chambers",
        "address": "119 NE Church Ave, White Salmon, WA 98672",
    }


def test_source():
    expected = (
        "https://www.whitesalmonwa.gov/civilservice/page/"
        "civil-service-commission-meeting-1"
    )
    assert parsed_item["source"] == expected


def test_links():
    links = parsed_item["links"]
    assert any(link["title"] == "Agenda" for link in links)


def test_all_day():
    assert parsed_item["all_day"] is False
